blank_issues_enabled: false
contact_links:
  - name: ðŸ“± NyanTV Help on Telegram
    url: https://t.me/NyanTVSupport
    about: Connect with the community, ask questions, and get help directly on Telegram.
