blank_issues_enabled: false
contact_links:
  - name: ğŸ“± NyanTV Help on Telegram
    url: https://t.me/NyanSupport
    about: Connect with the community, ask questions, and get help directly on Telegram.
  
  - name: ğŸ§‘â€ğŸ’» NyanTV Help on Stoat aka Revolt
    url: https://stoat.chat/invite/fKzse8yy
    about: Get support, ask questions, and join the community discussions.